language: node_js

node_js:
  - "10"

cache:
  directories:
    - ~/.npm

notifications:
  email: false

stages:
    - validation
    - release

jobs:
    include:
        - stage: validation
          name: "Lint"
          script:
                - npm run lint

        - stage: validation
          name: "Unit tests"
          if: branch != master
          node_js:
              - "8"  # Active LTS
              - "10" # Next LTS
              - "11" # Latest
          script:
              - npm test

        - stage: validation
          name: "Unit tests coverage"
          if: branch in (master, develop)
          node_js:
              - "8"  # Active LTS
              - "10" # Next LTS
              - "11" # Latest
          addons:
            sonarcloud:
              organization: "abrahamtewa-github"
          script:
            - npm run test-cov

            # Export coverage to coveralls.io
            - more reports/tests/unit/coverage/lcov.info | npx coveralls

            # Export coverage to codacy.com
            # Use variable: CODACY_PROJECT_TOKEN
            # See https://github.com/codacy/node-codacy-coverage#identifying-the-project
            - more reports/tests/unit/coverage/lcov.info | npx codacy-coverage

            # Perform sonar analysis on the coverage
            # Use variable: SONAR_TOKEN
            - sonar-scanner

        - stage: release
          name: "Release"
          if: branch = master
          deploy:
              provider: script
              skip_cleanup: true
              script:
                - npm run semantic-release

        - stage: release
          name: "Documentation"
          if: branch = master
          deploy:
                provider: pages
                skip-cleanup: true
                github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
                keep-history: true
                on:
                    branch: master
